### ISSUE TITLE
Store token registration and last successful notification timestamp in the database

### ISSUE THREAD

**Issue by link2xt** [chatmail/notifiers#15]
We currently have >14k valid tokens that are notified without errors. I don't expect that we have this many iOS users.

Would be nice to store registration timestamp in addition to the token and not notify it if it is too old.

**Comment by r10s** [comment]
> Would be nice to store registration timestamp in addition to the token and not notify it if it is too old.

i just discussed that with @zeitschlag:

- in normal usable, the tokens normally do not expire from apple side. the token expire only when the app is uninstalled uninstalled - and we seem to handle that by errors as mentioned in https://github.com/deltachat/notifiers/pull/13

- deltachat-ios requests the token on every app start unconditionally and gives it to the server/to the core, that seem to be best practise

so, expiring within a few days or even weeks will result in notifications not to work (esp. the new PUSH notification), as deltachat-ios does not have a chance to update the token.

expiration after several weeks or some months may make sense - but as it seems as if expired tokens result in an error anyways, that case is already caught.

>  I don't expect that we have this many iOS users.

we have over 63k downloads since we started in app-store and regularly more than 500 testflight users, so maybe the 14k tokens are still reasonable.

so, maybe wrt expiration everything's fine. but if the heartbeat does not work that way any longer, maybe we can also increase the timespan. it is somehow mainly needed to also remind apple to not forget "local wakeup" - when the app is really in used, i regularily get local wakeups every 20 minutes anyways.

with the "real PUSH", the heartbeat would become less important anyways, any maybe also can be tuned out over time

**Comment by r10s** [comment]
> I think we should at least store last registration date for the token and see how many tokens we have that are not re-registered for more than a month. 

makes sense, yes. at least to get a feeling and to gather some stats.

the main point is that we should not expire tokens within somehow reasonable days or weeks (user installed the app, gives the address to someone, they write back 4 weeks later where the keys for the flat are :)

> E.g. I have no idea what will happen to the token if device is factory-reset or just gets broken while the app is still installed.

i read somewhere that on device-reinstall / factory-reset, deltachat-ios will get a new token. i'd assume the old token to result in an error when trying to use that on the apple sever.

**Comment by hpk42** [comment]
Wouldn't WA or signal or telegram send more than 14k tokens to apple at once?   What exactly is the rate limit about? Is it per connection?  With 500 million active users there should be 100k iOS users getting notified at any time, no?
